---
progenetix:
  note: ""
  label: ""
  description: ""
  parameters:
    includeDatasetResponses:
      placeholder: "ALL"
      isHidden: true
    requestType:
      rules:
        required: false
      isHidden: true
    assemblyId:
      isHidden: true
    referenceName:
      placeholder: "9"
    start:
      placeholder: "19000001-21975098"
    end:
      placeholder: "21967753-24000000"
    variantType:
      placeholder: "DEL"
    materialtype:
      placeholder: "" #"EFO:0009656"
  examples:
    - label: "CDKN2A Deletion Example"
      note: "Example for focal CDKN2A deletion matches."
      description: |
        This example shows the query for CNV deletion variants overlapping the
        CDKN2A gene's coding region with at least a single base, but limited
        to "highly focal" hits (here i.e. <= ~1Mbp in size). The query is against the
        Progenetix and arrayMap collections. It can be modified e.g. through changing the position
        parameters or diagnosis.
      parameters:
        datasetIds:
          defaultValue: "progenetix"
        includeDatasetResponses:
          defaultValue: "ALL"
          isHidden: true
        assemblyId:
          defaultValue: "GRCh38"
          isHidden: true
        referenceName:
          defaultValue: "9"
        start:
          defaultValue: "21500001-21975098"
        end:
          defaultValue: "21967753-22500000"
        variantType:
          defaultValue: "DEL"
        bioontology:
          defaultValue: NCIT:C3058
