biofilters:
  NCIT:
    label: NCIT Cancer Core
  icdom:
    label: ICD-O Histology
  icdot:
    label: ICD-O Topography
  UBERON:
    label: UBERON Anatomy Ontology
  TNM:
    label: NCIT TNM Finding
cohortfilters:
  TCGA:
    label: The Cancer Genome Atlas (projects)
  cellosaurus:
    label: Cellosaurus Cell Line Resource
  cBP:
    label: cBioPortal Projects
  geo:
    label: Gene Expression Omnibus (Series and Platforms)
  PMID:
    label: Publications
datasetIds:
  progenetix:
    label: Progenetix
