---
variantAlleleRequest:
  note: "Example for specific EIF4A1 mutation"
  label: "Allele Request"
  description: |
    The **Beacon Allele Request** corresponds to the original Beacon query, in which
    variants with a specific combination of reference and alternate bases are being
    matched. "N" here can stand in as wildcard nucleotide.
  parameters:
    datasetIds:
      placeholder: "dipg"
    includeDatasetResponses:
      placeholder: "ALL"
      hide: true
    requestType:
      value: "variantAlleleRequest"
      hide: true
    assemblyId:
      placeholder: "GRCh38"
      hide: true
    geneinputField:
      placeholder: ""
      hide: true
    cytoinputField:
      placeholder: ""
      hide: true
    referenceName:
      placeholder: "17"
    start:
      placeholder: 7577121
    end:
      placeholder: ""
      hide: true
    variantType:
      placeholder: ""
      hide: true
    alternateBases:
      placeholder: "A"
    referenceBases:
      placeholder: "G"
    materialtype:
      placeholder: ""
      hide: true
    freeFilters:
      placeholder: ""
      hide: true
  examples:
    - label: "SNV Example"
      note: "Example for specific EIF4A1 mutation"
      description: |
        This example shows a core Beacon query, against a specific
        mutation in the EIF4A1 gene, in the DIPG childhood brain tumor dataset.
      parameters:
        datasetIds:
          value: "dipg"
        includeDatasetResponses:
          value: "ALL"
          hide: true
        assemblyId:
          value: "GRCh38"
        geneinputField:
          value: "EIF4A1"
          hide: true
        cytoinputField:
          value: ""
        referenceName:
          value: "17"
        start:
          value: 7577121
        end:
          value: ""
        variantType:
          value: ""
        alternateBases:
          value: "A"
        referenceBases:
          value: "G"
        freeFilters:
          value: ""
      ontology_queries:
        - "icdot-C71.7"
        - "NCIT"
        - "icdom"
        - "icdot"
    - label: "ClinVar Example"
      note: "Example for TP53 mutation (ClinVar annotated) in a cell line"
      description: |
        This example shows a core Beacon query, against a specific
        mutation in the TP53 gene, in cellosaurus, with ClinVar data.
      parameters:
        datasetIds:
          value: "cellosaurus"
        includeDatasetResponses:
          value: "ALL"
          hide: true
        assemblyId:
          value: "GRCh38"
        geneinputField:
          value: "TP53"
        cytoinputField:
          value: "17p13.1"
        referenceName:
          value: "17"
        start:
          value: 7673767
        endMin:
          value: ""
        end:
          value: ""
        variantType:
          value: ""
        alternateBases:
          value: "T"
        referenceBases:
          value: "C"
        materialtype:
          value: ""
          hide: true
        freeFilters:
          value: ""
      ontology_queries:
        - "NCIT"

variantCNVrequest:
  note: ""
  label: "CNV Request"
  description: |
    This query type is for copy number queries ("variantCNVrequest"), e.g. using fuzzy
    ranges for start and end positions to capture a set of similar variants.
  parameters:
    datasetIds:
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
      hide: true
    requestType:
      value: "variantCNVrequest"
      hide: true
    assemblyId:
      placeholder: "GRCh38"
    geneinputField:
      placeholder: "CDKN2A"
      hide: true
    cytoinputField:
      placeholder: ""
      hide: true
    referenceName:
      placeholder: "9"
    start:
      placeholder: "19000001-21975098"
    end:
      placeholder: "21967753-24000000"
    variantType:
      placeholder: "DEL"
    alternateBases:
      placeholder: ""
      hide: true
    referenceBases:
      placeholder: "N"
      hide: true
    materialtype:
      placeholder: "" #"EFO:0009656"
      hide: true
    freeFilters:
      placeholder: ""
      hide: true
  examples:
    - label: "CNV Example"
      note: "Example for focal CDKN2A deletion matches."
      description: |
        This example shows the query for CNV deletion variants overlapping the
        CDKN2A gene's coding region with at least a single base, but limited
        to "focal" hits (here i.e. <= ~2Mbp in size). The query is against the
        arrayMap collection and can be modified e.g. through changing the position
        parameters or data source.
      parameters:
        datasetIds:
          value: "arraymap"
        includeDatasetResponses:
          value: "ALL"
          hide: true
        assemblyId:
          value: "GRCh38"
        geneinputField:
          value: "CDKN2A"
        referenceName:
          value: "9"
        start:
          value: "21000001-21975098"
        end:
          value: "21967753-23000000"
        variantType:
          value: "DEL"
        alternateBases:
          value: ""
          hide: true
        referenceBases:
          value: "N"
          hide: true
        bioontology:
          value: NCIT:C3058
        freeFilters:
          value: ""
          hide: true
      ontology_queries:
        - "icdom"
        - "NCIT"

variantRangeRequest:
  note: ""
  label: "Range Query"
  description: |
    Range + wildcard query will return any variant between the given positions. Either a
    "variant type" or alternate bases ("N" for wildcard) should be specified.
    The exact variants which were being found can be retrieved through the variant
    handover [H—>O] link.
  parameters:
    datasetIds:
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
      hide: true
    requestType:
      value: "variantRangeRequest"
      hide: true
    assemblyId:
      placeholder: "GRCh38"
    geneinputField:
      placeholder: ""
      hide: true
    cytoinputField:
      placeholder: ""
      hide: true
    referenceName:
      placeholder: "17"
    start:
      placeholder: 7572826
    end:
      placeholder: 7579005
    variantType:
      placeholder: ""
    alternateBases:
      placeholder: "N"
    referenceBases:
      placeholder: "N"
  examples:
    - label: "SNV Range Example"
      note: "Example for EIF4A1 transcript region matches (precise variants)"
      description: |
        As in the standard SNV query, this example shows a Beacon query against
        mutations in the EIF4A1 gene in the DIPG childhood brain tumor dataset.
        However, this range + wildcard query will return any variant with
        alternate bases (indicated through "N").
        Since parameters will be interpreted using an "AND" paradigm, either <i>Alternate
        Bases</i> OR <i>Variant Type</i> should be specified.
        The exact variants which were being found can be retrieved through the variant
        handover [H—>O] link.
      parameters:
        datasetIds:
          value: "dipg"
        includeDatasetResponses:
          value: "ALL"
          hide: true
        assemblyId:
          value: "GRCh38"
        geneinputField:
          value: "EIF4A1"
        referenceName:
          value: "17"
        start:
          value: 7572826
        end:
          value: 7579005
        variantType:
          value: ""
        alternateBases:
          value: "N"
        referenceBases:
          value: "N"
        freeFilters:
          value: ""
      ontology_queries:
        - "NCIT"
        - "icdom"
        - "icdot"


allFieldsRequest:
  note: ""
  label: "All Fields"
  description: |
    All form fields for composing your own queries.
  parameters:
    datasetIds:
      placeholder: ""
    includeDatasetResponses:
      placeholder: "ALL"
    requestType:
    assemblyId:
      placeholder: "GRCh38"
    geneinputField:
      placeholder: "CDKN2A"
    cytoinputField:
      placeholder: "9p13.1"
    referenceName:
      placeholder: "9"
    start:
      placeholder: "20000001-21975098"
    startMax:
      placeholder: 21975098
    endMin:
      placeholder: 21967753
    end:
      placeholder: "21967753-23000000"
    variantType:
      placeholder: "DEL"
    alternateBases:
      placeholder: "A"
    referenceBases:
      placeholder: "G"
    freeFilters:
      placeholder: "" # "geolat:49,geolong:8.69,geodist:2000000"
    materialtype:
      placeholder: "" #"EFO:0009656"
